"use client";
import { FormEvent, useMemo, useState } from "react";
import { Copy, Plus, Tag, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Category={id:string;name:string;code:string|null;status:string;sort_order:number;settings:Record<string,unknown>};
type Competition={id:string;name:string;model:string;status:string;categories:Category[]};
export default function CategoryManager({initialCompetitions}:{eventId:string;initialCompetitions:Competition[]}){
  const [competitions,setCompetitions]=useState(initialCompetitions); const [selected,setSelected]=useState(initialCompetitions[0]?.id||""); const [open,setOpen]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const current=useMemo(()=>competitions.find((item)=>item.id===selected),[competitions,selected]);
  async function createCategory(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const settings={sex:String(form.get("sex")||"open"),age_min:Number(form.get("age_min"))||null,age_max:Number(form.get("age_max"))||null,level:String(form.get("level")||""),graduation_min:String(form.get("graduation_min")||""),graduation_max:String(form.get("graduation_max")||""),awards:String(form.get("awards")||"")};const {data,error:insertError}=await createClient().from("categories").insert({competition_id:selected,name:String(form.get("name")||""),code:String(form.get("code")||""),status:"draft",sort_order:(current?.categories.length||0)+1,settings}).select("id,name,code,status,sort_order,settings").single();if(insertError||!data){setError(insertError?.message||"Não foi possível criar a categoria.");setLoading(false);return;}setCompetitions((items)=>items.map((item)=>item.id===selected?{...item,categories:[...item.categories,data as Category]}:item));setOpen(false);setLoading(false);}
  async function duplicate(category:Category){const {data}=await createClient().from("categories").insert({competition_id:selected,name:`${category.name} (cópia)`,code:category.code?`${category.code}-COPIA`:null,status:"draft",sort_order:(current?.categories.length||0)+1,settings:category.settings}).select("id,name,code,status,sort_order,settings").single();if(data)setCompetitions((items)=>items.map((item)=>item.id===selected?{...item,categories:[...item.categories,data as Category]}:item));}
  return <section className="category-workspace"><div className="competition-switcher">{competitions.map((competition)=><button className={competition.id===selected?"active":""} onClick={()=>setSelected(competition.id)} key={competition.id}><strong>{competition.name}</strong><span>{competition.model==="sum_score"?"Somatório de notas":"Bandeiras digitais"} · {competition.categories.length} categoria(s)</span></button>)}</div><div className="category-toolbar"><div><span className="eyebrow">COMPETIÇÃO SELECIONADA</span><h2>{current?.name}</h2><p>Categorias permanecem separadas das outras competições do evento.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus/>Nova categoria</button></div>{current?.categories.length?<div className="category-table">{current.categories.map((category)=><article key={category.id}><div className="category-icon"><Tag/></div><div><strong>{category.name}</strong><span>{category.code||"Sem código"} · {String(category.settings.sex||"open")==="open"?"Sexo livre":String(category.settings.sex)}</span></div><b>Rascunho</b><button title="Duplicar categoria" onClick={()=>duplicate(category)}><Copy/></button></article>)}</div>:<div className="empty-state compact"><Tag/><h2>Nenhuma categoria nesta competição</h2><p>Cadastre categorias próprias para {current?.name}.</p><button className="primary" onClick={()=>setOpen(true)}><Plus/>Cadastrar categoria</button></div>}{open&&<div className="modal-wrap"><button className="backdrop" onClick={()=>setOpen(false)} aria-label="Fechar"/><form className="modal category-modal" onSubmit={createCategory}><button type="button" className="modal-x" onClick={()=>setOpen(false)}><X/></button><span className="eyebrow">{current?.name}</span><h2>Nova categoria</h2><div className="form-grid"><label className="wide">Nome<input name="name" required placeholder="Ex.: Adulto Avançado"/></label><label>Código<input name="code" placeholder="AD-AV"/></label><label>Sexo<select name="sex"><option value="open">Livre</option><option value="masculino">Masculino</option><option value="feminino">Feminino</option></select></label><label>Idade mínima<input name="age_min" type="number" min="0"/></label><label>Idade máxima<input name="age_max" type="number" min="0"/></label><label>Nível<input name="level" placeholder="Iniciante, avançado..."/></label><label>Graduação mínima<input name="graduation_min"/></label><label>Graduação máxima<input name="graduation_max"/></label><label className="wide">Premiação<input name="awards" placeholder="Medalha, troféu, bicicleta..."/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={loading}>{loading?"Salvando...":"Salvar categoria"}</button></div></form></div>}</section>;
}
